var MidtsDriveService = (function () {
  function ensureLeadStructure(leadId) {
    if (!leadId) throw new Error('Lead ID is required for Drive folder setup.');

    var root = getRootFolder_();
    var leadFolder = getOrCreateFolder_(root, 'Lead_' + leadId);
    var vendorSafeFolder = getOrCreateFolder_(leadFolder, 'Vendor Safe');
    var quotesFolder = getOrCreateFolder_(leadFolder, 'Quotes');

    return {
      leadFolderId: leadFolder.getId(),
      leadFolderUrl: leadFolder.getUrl(),
      vendorSafeFolderId: vendorSafeFolder.getId(),
      vendorSafeFolderUrl: vendorSafeFolder.getUrl(),
      quotesFolderId: quotesFolder.getId(),
      quotesFolderUrl: quotesFolder.getUrl()
    };
  }

  function saveClientIntakeFiles(leadId, files) {
    if (!leadId) throw new Error('Lead ID is required for client intake files.');
    if (!Array.isArray(files) || !files.length) {
      return {
        folderUrl: '',
        fileLinks: [],
        files: []
      };
    }

    var structure = ensureLeadStructure(leadId);
    var leadFolder = DriveApp.getFolderById(structure.leadFolderId);
    var intakeFolder = getOrCreateFolder_(leadFolder, 'Client Intake Files');
    var savedFiles = [];

    files.forEach(function (file, index) {
      var name = sanitizeFilename_(file && file.name || 'intake-file-' + (index + 1));
      var contentBase64 = String(file && file.contentBase64 || '').trim();
      if (!contentBase64) return;

      var contentType = String(file && file.type || 'application/octet-stream').trim() || 'application/octet-stream';
      var bytes = Utilities.base64Decode(contentBase64);
      var blob = Utilities.newBlob(bytes, contentType, name);
      var driveFile = intakeFolder.createFile(blob);
      savedFiles.push({
        name: name,
        type: contentType,
        sizeBytes: Number(file && file.sizeBytes || bytes.length),
        driveFileId: driveFile.getId(),
        driveUrl: driveFile.getUrl()
      });
    });

    return {
      folderUrl: intakeFolder.getUrl(),
      fileLinks: savedFiles.map(function (file) { return file.driveUrl; }),
      files: savedFiles
    };
  }

  function getQuotesFolder(leadId) {
    var structure = ensureLeadStructure(leadId);
    return DriveApp.getFolderById(structure.quotesFolderId);
  }

  function getVendorSafeFolder(leadId) {
    var structure = ensureLeadStructure(leadId);
    return DriveApp.getFolderById(structure.vendorSafeFolderId);
  }

  function getVendorSafePackageFolder(leadId, packageId) {
    var vendorSafeFolder = getVendorSafeFolder(leadId);
    return getOrCreateFolder_(vendorSafeFolder, sanitizeFolderName_(packageId || 'Vendor Safe Package'));
  }

  function createGoogleDocInFolder(folder, title, sections) {
    var safeTitle = sanitizeFilename_(title || 'MIDTS Document');
    var doc = DocumentApp.create(safeTitle);
    var body = doc.getBody();
    body.clear();

    body.appendParagraph(safeTitle).setHeading(DocumentApp.ParagraphHeading.HEADING1);
    body.appendParagraph('Generated by MIDTS').setItalic(true);
    body.appendParagraph('');

    (sections || []).forEach(function (section) {
      if (section && section.heading) body.appendParagraph(String(section.heading)).setHeading(DocumentApp.ParagraphHeading.HEADING2);
      (section && section.lines || []).forEach(function (line) {
        body.appendParagraph(String(line || ''));
      });
      body.appendParagraph('');
    });

    doc.saveAndClose();
    var file = DriveApp.getFileById(doc.getId());
    folder.addFile(file);
    try { DriveApp.getRootFolder().removeFile(file); } catch (error) {}

    return {
      name: safeTitle,
      id: file.getId(),
      url: file.getUrl(),
      mimeType: MimeType.GOOGLE_DOCS
    };
  }

  function copyFilesByUrl(fileUrls, targetFolder) {
    var copied = [];
    (fileUrls || []).forEach(function (url, index) {
      var fileId = extractDriveFileId_(url);
      if (!fileId) return;
      try {
        var sourceFile = DriveApp.getFileById(fileId);
        var copy = sourceFile.makeCopy(sanitizeFilename_(sourceFile.getName() || 'Client File ' + (index + 1)), targetFolder);
        copied.push({ name: copy.getName(), id: copy.getId(), url: copy.getUrl() });
      } catch (error) {
        copied.push({ name: 'File copy failed', id: '', url: String(url || ''), error: String(error && error.message ? error.message : error) });
      }
    });
    return copied;
  }

  function extractDriveFileId_(url) {
    var text = String(url || '').trim();
    if (!text) return '';
    var match = text.match(/\/d\/([a-zA-Z0-9_-]+)/) || text.match(/[?&]id=([a-zA-Z0-9_-]+)/) || text.match(/file\/([a-zA-Z0-9_-]+)/);
    return match ? match[1] : '';
  }

  function getRootFolder_() {
    var rootId = MidtsConfig.getRequiredScriptProperty('DRIVE_ROOT_FOLDER_ID');
    return DriveApp.getFolderById(rootId);
  }

  function getOrCreateFolder_(parent, name) {
    var matches = parent.getFoldersByName(name);
    return matches.hasNext() ? matches.next() : parent.createFolder(name);
  }

  function sanitizeFolderName_(name) {
    return String(name || 'Folder').replace(/[\\/:*?"<>|]+/g, '-').replace(/\s+/g, ' ').trim() || 'Folder';
  }

  function sanitizeFilename_(name) {
    var cleaned = String(name || 'intake-file').replace(/[\\/:*?"<>|]+/g, '-').replace(/\s+/g, ' ').trim();
    return cleaned || 'intake-file';
  }

  return {
    ensureLeadStructure: ensureLeadStructure,
    saveClientIntakeFiles: saveClientIntakeFiles,
    getQuotesFolder: getQuotesFolder,
    getVendorSafeFolder: getVendorSafeFolder,
    getVendorSafePackageFolder: getVendorSafePackageFolder,
    createGoogleDocInFolder: createGoogleDocInFolder,
    copyFilesByUrl: copyFilesByUrl
  };
})();
